" vimrc file for vim configuration, 18-02-2019, Prakash Acharya

" set imcompatible with vi
set nocompatible

" use 4 spaces for tab
set expandtab
set tabstop=4

" insert four spaces when giving > command
set shiftwidth=4

" set relative line number on the left and set the width to 1
set number
set relativenumber
set numberwidth=1

" enable syntax highlighting and set modeline
syntax on
set modeline
set modelines=5

" set tab completion to something similar to bash
set wildmode=longest,list

" When searching try to be smart about cases
set ignorecase
set smartcase

" show matching bracket
set showmatch

" set terminal title
set title

" no bells
set novisualbell
set noerrorbells

" show incremental search pattern
set incsearch
set hls
highlight Search cterm=None ctermfg=yellow ctermbg=black

" remember more commands
set history=500

"map up and down key for Ctrl-p and Ctrl-n
cnoremap <C-p> <Up>
cnoremap <C-n> <Down>

" add common suffixes for gf command
set suffixesadd=.py

" make scrolling easier
set scrolloff=3

" make tabs and trailing whitespace visible
set list
set listchars=tab:→\ ,trail:•,nbsp:•

" string to put at the start of the wrapped lines
let &showbreak="↪\ "

if expand('%:t') == "COMMIT_EDITMSG"
    set colorcolumn=73
else
    set colorcolumn=80
endif
